-- 새 Supabase 프로젝트 SQL Editor에서 1회 실행 (001~007 통합)
-- 프로젝트: https://aqdmuqegokwecclcqhgc.supabase.co

-- ========== 001_initial.sql ==========
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  client_name text not null,
  phone text not null,
  email text not null,
  message text default '',
  business_type text not null,
  area text not null,
  budget text not null,
  estimate_min int,
  estimate_max int,
  status text not null default '신규',
  created_at timestamptz default now()
);

create table if not exists public.portfolios (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  area text not null,
  budget text not null,
  industry text not null,
  style text not null,
  duration text not null,
  image_url text not null,
  created_at timestamptz default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  business text not null,
  rating int not null default 5,
  comment text not null,
  image text not null,
  created_at timestamptz default now()
);

alter table public.leads enable row level security;
alter table public.portfolios enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "leads read" on public.leads;
drop policy if exists "leads insert" on public.leads;
drop policy if exists "leads update" on public.leads;
drop policy if exists "portfolios read" on public.portfolios;
drop policy if exists "portfolios insert" on public.portfolios;
drop policy if exists "portfolios update" on public.portfolios;
drop policy if exists "portfolios delete" on public.portfolios;
drop policy if exists "reviews read" on public.reviews;
drop policy if exists "reviews insert" on public.reviews;

create policy "leads read" on public.leads for select using (true);
create policy "leads insert" on public.leads for insert with check (true);
create policy "leads update" on public.leads for update using (true);

create policy "portfolios read" on public.portfolios for select using (true);
create policy "portfolios insert" on public.portfolios for insert with check (true);
create policy "portfolios update" on public.portfolios for update using (true);
create policy "portfolios delete" on public.portfolios for delete using (true);

create policy "reviews read" on public.reviews for select using (true);
create policy "reviews insert" on public.reviews for insert with check (true);

-- ========== 002_site_settings.sql ==========
create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz default now()
);

alter table public.site_settings enable row level security;

drop policy if exists "site_settings read" on public.site_settings;
drop policy if exists "site_settings insert" on public.site_settings;
drop policy if exists "site_settings update" on public.site_settings;

create policy "site_settings read" on public.site_settings for select using (true);
create policy "site_settings insert" on public.site_settings for insert with check (true);
create policy "site_settings update" on public.site_settings for update using (true);

insert into public.site_settings (key, value) values (
  'hero_image_url',
  'https://images.unsplash.com/photo-1585503081214-2d3384d1f7b0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080'
) on conflict (key) do nothing;

-- ========== 003 + 006 + 007 portfolio extras ==========
alter table public.portfolios
  add column if not exists image_urls jsonb default '[]'::jsonb;

alter table public.portfolios
  add column if not exists remark_title text not null default '';

alter table public.portfolios
  add column if not exists remark_body text not null default '';

-- ========== 005_storage_portfolio_images_policies.sql ==========
insert into storage.buckets (id, name, public)
values ('portfolio-images', 'portfolio-images', true)
on conflict (id) do nothing;

drop policy if exists "public read portfolio images" on storage.objects;
drop policy if exists "public upload portfolio images" on storage.objects;
drop policy if exists "public update portfolio images" on storage.objects;
drop policy if exists "public delete portfolio images" on storage.objects;

create policy "public read portfolio images"
on storage.objects for select to public
using (bucket_id = 'portfolio-images');

create policy "public upload portfolio images"
on storage.objects for insert to public
with check (bucket_id = 'portfolio-images');

create policy "public update portfolio images"
on storage.objects for update to public
using (bucket_id = 'portfolio-images')
with check (bucket_id = 'portfolio-images');

create policy "public delete portfolio images"
on storage.objects for delete to public
using (bucket_id = 'portfolio-images');
